package days.day10

enum MapTile:
  case
    STARTING_POSITION,
    GROUND,
    VERTICAL_PIPE,
    HORIZONTAL_PIPE,
    NORTH_AND_EAST_PIPE,
    NORTH_AND_WEST_PIPE,
    SOUTH_AND_EAST_PIPE,
    SOUTH_AND_WEST_PIPE
